# Generated by Django 3.2.18 on 2023-02-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_docotrs_dep_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docotrs',
            name='dep_id',
        ),
    ]
