# Generated by Django 3.2.18 on 2023-03-01 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_timeslots'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlots',
        ),
    ]
