# Generated by Django 3.2.18 on 2023-03-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_delete_timeslots'),
    ]

    operations = [
        migrations.AddField(
            model_name='docotrs',
            name='email',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='docotrs',
            name='password',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
