# Generated by Django 4.1.2 on 2023-03-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0008_remove_departments_dep_id'),
        ('doctor', '0014_auto_20230308_1639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Docotrs',
            new_name='Doctor',
        ),
    ]
