# Generated by Django 3.2.18 on 2023-03-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_rename_docotrs_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='lname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
