# Generated by Django 3.2.18 on 2023-04-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalService', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalservices',
            name='img',
        ),
        migrations.RemoveField(
            model_name='hospitalservices',
            name='name',
        ),
        migrations.AddField(
            model_name='hospitalservices',
            name='Age',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='hospitalservices',
            name='Date',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='hospitalservices',
            name='Description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hospitalservices',
            name='Time',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='hospitalservices',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalservices',
            name='availability',
            field=models.CharField(default='', max_length=3),
        ),
    ]
