# Generated by Django 3.2.18 on 2023-03-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentsMdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeSlot', models.CharField(max_length=10)),
                ('dateSlot', models.CharField(max_length=10)),
                ('userId', models.CharField(max_length=10)),
                ('doctorId', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
