# Generated by Django 3.2.18 on 2023-03-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsmdel',
            name='dateSlot',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='appointmentsmdel',
            name='doctorId',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='appointmentsmdel',
            name='status',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='appointmentsmdel',
            name='timeSlot',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='appointmentsmdel',
            name='userId',
            field=models.CharField(max_length=25),
        ),
    ]
