# Generated by Django 3.2.18 on 2023-03-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_appointmentsmdel_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsmdel',
            name='doctorName',
            field=models.CharField(default='default', max_length=25),
        ),
        migrations.AddField(
            model_name='appointmentsmdel',
            name='patientName',
            field=models.CharField(default='default', max_length=25),
        ),
    ]
