# Generated by Django 4.1.2 on 2023-03-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20230309_1318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentsMdel',
            new_name='AppointmentsModel',
        ),
    ]
