# Generated by Django 3.2.18 on 2023-02-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='img',
            field=models.TextField(),
        ),
    ]
