# Generated by Django 3.2.18 on 2023-03-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='', max_length=20)),
                ('userEmail', models.CharField(default='', max_length=20)),
                ('doctorId', models.CharField(default='', max_length=10)),
                ('rating', models.CharField(default='', max_length=10)),
                ('description', models.CharField(default='', max_length=10)),
                ('viwedByDoctor', models.CharField(default='', max_length=10)),
                ('viwedByAdmin', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
