# Generated by Django 3.2.18 on 2023-04-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0002_auto_20230428_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ehr',
            name='age',
        ),
        migrations.RemoveField(
            model_name='ehr',
            name='document',
        ),
        migrations.RemoveField(
            model_name='ehr',
            name='gender',
        ),
    ]
