# Generated by Django 3.2.18 on 2023-03-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='quantity',
            new_name='inStock',
        ),
    ]
