# Generated by Django 3.2.18 on 2023-04-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ehrId', models.CharField(default='default', max_length=60)),
                ('documentLink', models.CharField(default='default', max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
