# Generated by Django 3.2.18 on 2023-04-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='created_at',
            field=models.CharField(default='00/00/00', max_length=10),
        ),
    ]
