# Generated by Django 3.2.18 on 2023-03-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20230301_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsmdel',
            name='approved',
            field=models.CharField(default='default', max_length=10),
        ),
    ]
