# Generated by Django 3.2.18 on 2023-03-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('price', models.CharField(default='', max_length=10)),
                ('quantity', models.CharField(default='', max_length=10)),
                ('provider', models.CharField(default='', max_length=10)),
                ('manufacturing_date', models.CharField(default='', max_length=10)),
                ('availablity', models.CharField(default='', max_length=10)),
                ('description', models.CharField(default='', max_length=80)),
                ('more', models.CharField(default='', max_length=80)),
            ],
        ),
    ]
