# Generated by Django 3.2.18 on 2023-03-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_rename_quantity_medicine_instock'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='expiration_date',
            field=models.CharField(default='', max_length=80),
        ),
    ]
