# Generated by Django 3.2.18 on 2023-04-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lname', models.CharField(default='', max_length=20)),
                ('qualification', models.CharField(max_length=30)),
                ('availability', models.BooleanField()),
                ('email', models.CharField(default='default', max_length=20)),
                ('password', models.CharField(default='default', max_length=20)),
                ('year_of_experience', models.IntegerField()),
            ],
        ),
    ]
