# Generated by Django 3.2.18 on 2023-04-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_auto_20230428_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehr',
            name='ehr_id',
            field=models.CharField(default='', max_length=60),
        ),
    ]
