# Generated by Django 3.2.18 on 2023-02-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='img',
            field=models.ImageField(default=None, upload_to='appUploads'),
        ),
    ]
