# Generated by Django 3.2.18 on 2023-02-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_departments_departments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='departments_id',
            field=models.CharField(default='00X', max_length=10),
        ),
    ]
