# Generated by Django 3.2.18 on 2023-02-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docotrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=30)),
                ('img', models.ImageField(default=None, upload_to='appUploads')),
                ('availability', models.BooleanField()),
                ('year_of_experience', models.IntegerField(max_length=2)),
            ],
        ),
    ]
