# Generated by Django 3.2.18 on 2023-02-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docotrs',
            name='year_of_experience',
            field=models.IntegerField(),
        ),
    ]
