# Generated by Django 3.2.18 on 2023-02-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_docotrs_departments_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docotrs',
            old_name='departments_id',
            new_name='dep_id',
        ),
    ]
