# Generated by Django 3.2.18 on 2023-02-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_rename_departments_id_docotrs_dep_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docotrs',
            name='dep_id',
            field=models.CharField(default='00X', max_length=10),
        ),
    ]
