# Generated by Django 3.2.18 on 2023-02-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_remove_docotrs_dep_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='docotrs',
            name='dep_id',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
