# Generated by Django 3.2.18 on 2023-03-01 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_timeslots'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlots',
        ),
    ]
